#pragma once

#include <string>

namespace cac {

class TaskGraph;
class KnowledgeBase;
class InputDesc;

// TODO: candidates file will go away (should be per kernel, and
// will be generated by the compilation flow)
int tune(TaskGraph &tg, KnowledgeBase &db, InputDesc &inputDesc,
		const std::string &modelsDir, const std::string &candidatesFile);

} // namespace cac;
