#ifndef CAC_CASPER_H
#define CAC_CASPER_H

// Include complete types, so that users can use them via this one header
#include "TaskGraph.h"
#include "Options.h"
#include "CasperHalide.h"

namespace cac {

// throws on failure
void compile(TaskGraph &tg, const std::string &platformFile,
		// TODO: eventually, these will go away from here because they
		// will be generated by the compilation flow
		const std::string &modelFile,const std::string &modelCPFile,
		const std::string &candidatesFile);

// compile() wrapped in a try/catch that returns non-zero on failure
int tryCompile(TaskGraph &tg, const std::string &platformFile,
		// TODO: eventually, these will go away from here because they
		// will be generated by the compilation flow
		const std::string &modelFile, const std::string &modelCPFile,
		const std::string &candidatesFile);

} // namespace cac

#endif // CAC_CASPER_H
